# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "100fea81ae8560c6fb113b1f6bb20857a41a5705";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "100fea81ae8560c6fb113b1f6bb20857a41a5705";
      fetchSubmodules = false;
      sha256 = "sha256-rb8bd7KjON2+aZ2pE9yyjNT2jaZPIbzVPDYW7dvJMLU=";
    };
    date = "2025-05-14";
  };
}
