# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "b9e63743a858766c9cc7a801d77313b0cecdb049";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "b9e63743a858766c9cc7a801d77313b0cecdb049";
      fetchSubmodules = false;
      sha256 = "sha256-XuFvCBOIiLncgsDZJJjU/qSSJJ5SfNF16pIJjIWUJ+A=";
    };
    date = "2025-06-21";
  };
}
