# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mpv-smartskip = {
    pname = "mpv-smartskip";
    version = "082797789eabc68fbe71de2cd0eee46a6b073503";
    src = fetchFromGitHub {
      owner = "Eisa01";
      repo = "mpv-scripts";
      rev = "082797789eabc68fbe71de2cd0eee46a6b073503";
      fetchSubmodules = false;
      sha256 = "sha256-krHyufDHVwuPdcotkbYnunKeEYHHb+08GqaruIzHclM=";
    };
    date = "2025-05-11";
  };
}
