# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swww = {
    pname = "swww";
    version = "3e2ea80f7beda0d222db5acaf768efbc3800aee9";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "3e2ea80f7beda0d222db5acaf768efbc3800aee9";
      fetchSubmodules = false;
      sha256 = "sha256-h+hBelFhaf3NIwjxBjUWco+hhvO5xwzdcWaPtBWWweI=";
    };
    date = "2025-04-03";
  };
  wallust = {
    pname = "wallust";
    version = "bc61a37944922535d651dad5399c1f951178ce51";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust";
      rev = "bc61a37944922535d651dad5399c1f951178ce51";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-co/8OFMfXICjpxkONpavU3t0YtXDkAf70ZuGKU3VnEI=";
    };
    date = "2025-04-12";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "7112e9139510978c099d9bc1f0ea21d8155ba72f";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "7112e9139510978c099d9bc1f0ea21d8155ba72f";
      fetchSubmodules = false;
      sha256 = "sha256-LKI2fFpzMtju3tF85AqbeJbNhvnIa7rnySUMZ4f/kJ8=";
    };
    date = "2025-04-12";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
      fetchSubmodules = false;
      sha256 = "sha256-ZZgn5rsBzvZcnDWZfjMBPRg9QUz4FTq5UIPWfnwXHQs=";
    };
    date = "2025-02-14";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2025.03.31";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2025.03.31";
      fetchSubmodules = false;
      sha256 = "sha256-csw91VbzY9IursMQFGwnlobZI3U6QOBDo31oq+X0ETI=";
    };
  };
}
