# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swww = {
    pname = "swww";
    version = "3e2ea80f7beda0d222db5acaf768efbc3800aee9";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "3e2ea80f7beda0d222db5acaf768efbc3800aee9";
      fetchSubmodules = false;
      sha256 = "sha256-h+hBelFhaf3NIwjxBjUWco+hhvO5xwzdcWaPtBWWweI=";
    };
    date = "2025-04-03";
  };
  wallust = {
    pname = "wallust";
    version = "afcbdec7fedfd5ac61faf6610682e2cc6c1cef4d";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust";
      rev = "afcbdec7fedfd5ac61faf6610682e2cc6c1cef4d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9QWsWT6TVpkem2vwoAOTsyXGvIzmtremAlmLr9ELjwE=";
    };
    date = "2025-05-11";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
      fetchSubmodules = false;
      sha256 = "sha256-v/C+ZBrF1ghDt1SXpZcDELmHMVAqfr44iWxzUWynyRk=";
    };
    date = "2025-05-11";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "7e0179e15a41a4a42b6d0b5fa6dd240c9b4cf0d2";
      fetchSubmodules = false;
      sha256 = "sha256-ZZgn5rsBzvZcnDWZfjMBPRg9QUz4FTq5UIPWfnwXHQs=";
    };
    date = "2025-02-14";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2025.04.30";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2025.04.30";
      fetchSubmodules = false;
      sha256 = "sha256-vsMWzZu+kxlxYT5Cq+diNApzE3Cg22Hg0j9eDKLowWI=";
    };
  };
}
