# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  path-of-building = {
    pname = "path-of-building";
    version = "v2.49.3";
    src = fetchFromGitHub {
      owner = "PathOfBuildingCommunity";
      repo = "PathOfBuilding";
      rev = "v2.49.3";
      fetchSubmodules = false;
      sha256 = "sha256-ZpvSI3W2pWPy37PDT4T4NpgFSoS7bk5d59vvCL2nWnM=";
    };
  };
  swww = {
    pname = "swww";
    version = "3e2e2ba8f44469a1446138ee97d2988e22b093bf";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "3e2e2ba8f44469a1446138ee97d2988e22b093bf";
      fetchSubmodules = false;
      sha256 = "sha256-XBwgv80YfLZ70XYVEnR0nA7Rz5jP241D5FiwrTg7tDk=";
    };
    date = "2025-01-17";
  };
  wallust = {
    pname = "wallust";
    version = "82236e6411cf6c862ce559649d9bebb011a0f18a";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust";
      rev = "82236e6411cf6c862ce559649d9bebb011a0f18a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-eA88BSqj748sLRRHTgiXCNDCwfxybdUi8xh/bbD4tjU=";
    };
    date = "2025-01-19";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "7707c09f03e02144e528625ba82f54c6177715b2";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "7707c09f03e02144e528625ba82f54c6177715b2";
      fetchSubmodules = false;
      sha256 = "sha256-oWdptgAtTAHX5u7lYe1o2TlvyCiOsuV1D5gm85J4dSE=";
    };
    date = "2025-01-19";
  };
  yazi-time-travel = {
    pname = "yazi-time-travel";
    version = "85baafd0b18515ccf0851e8d35f9306ec98f3c40";
    src = fetchFromGitHub {
      owner = "iynaix";
      repo = "time-travel.yazi";
      rev = "85baafd0b18515ccf0851e8d35f9306ec98f3c40";
      fetchSubmodules = false;
      sha256 = "sha256-kOpj/GJ7xIFfJDsuTvced5MYiC4ZLA0TgsqvcRnyALI=";
    };
    date = "2024-12-13";
  };
  yt-dlp = {
    pname = "yt-dlp";
    version = "2025.01.15";
    src = fetchFromGitHub {
      owner = "yt-dlp";
      repo = "yt-dlp";
      rev = "2025.01.15";
      fetchSubmodules = false;
      sha256 = "sha256-d9RGlANDkjRInIVADCrzx8+wn4wVc04J7Wn0c1q4N7k=";
    };
  };
}
