_: {
  imports = [
    ./3dprinting.nix
    ./brave.nix
    ./dunst.nix
    ./emacs.nix
    ./game-dev.nix
    ./gaming.nix
    ./gamma.nix
    ./ghostty.nix
    ./gtk.nix
    ./librewolf.nix
    ./mpv.nix
    ./nemo.nix
    ./nixcord.nix
    ./obs-studio.nix
    ./pathofbuilding.nix
    ./pqiv.nix
    ./qt.nix
    ./rofi.nix
    ./study.nix
    ./vlc.nix
    ./vscode.nix
    ./wallust.nix
    ./waybar.nix
    ./weeb
    ./wm.nix
    ./zathura.nix
    ./zoom.nix
  ];
}
