_: {
  imports = [
    ./hyprland
    ./niri
    ./wm
    ./3dprinting.nix
    ./brave.nix
    ./emacs.nix
    ./game-dev.nix
    ./gaming.nix
    ./gamma.nix
    ./ghostty.nix
    ./gtk.nix
    ./librewolf.nix
    ./mpv.nix
    ./nemo.nix
    ./nixcord.nix
    ./obs-studio.nix
    ./pathofbuilding.nix
    ./plasma.nix
    ./pqiv.nix
    ./qt.nix
    ./rofi.nix
    ./study.nix
    ./vlc.nix
    ./weeb
    ./vscode.nix
    ./zathura.nix
    ./zoom.nix
  ];
}
