# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  inputs,
  lib,
  ...
}:
{
  imports = [ inputs.nixos-hardware.nixosModules.lenovo-thinkpad-t520 ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "thunderbolt"
      "usb_storage"
      "sd_mod"
      "xhci_pci" # USB 3.0 controller
      "ehci_pci" # USB 2.0 controller fallback
      "ahci" # SATA controller
      "usb_storage" # USB storage
      "sd_mod" # SD card / SCSI disk support
      "rtsx_pci_sdmmc" # Realtek SD card reader
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "iwlwifi" ];
    extraModulePackages = [ ];
  };

  # Enable firmware update module
  services.fwupd.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;
  hardware.enableRedistributableFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
