# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  inputs,
  lib,
  ...
}:
{
  imports = [ inputs.nixos-hardware.nixosModules.lenovo-thinkpad-t520 ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci" # USB 3.0
      "ehci_pci" # USB 2.0 fallback
      "ahci" # SATA controller
      "nvme" # in case of SSD upgrade
      "usbhid" # USB keyboard/mouse
      "usb_storage" # USB drives
      "sd_mod" # SCSI disk support
      "rtsx_pci_sdmmc" # Realtek SD reader
      "sr_mod" # Optical drive (CD/DVD)
      "ata_generic"
      "pata_acpi"
    ];

    kernelModules = [
      "iwlwifi" # Intel wireless
      "thinkpad_acpi" # Fn keys, fan, LEDs
      "coretemp" # CPU temps for monitoring
      "kvm-intel" # virtualization
    ];

    extraModulePackages = [ ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted
  # networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
